### ISSUE TITLE
node_modules directory not created using dockerfile example. No error messages

### ISSUE THREAD

**Issue by eric-naguras** [keymetrics/docker-pm2#42] opened 2017-11-06 09:29 UTC
I'm using your dockerfile as suggested on https://hub.docker.com/r/keymetrics/pm2/ but there is no node_modules directory created.

my docker version is  17.09.0-ce, build afdb6d4

Below is the output of the docker build command. As you can see there is no node_modules so the javascript program will fail with module xxx not found.

When I run the container interactively (first installing a bash shell with RUN apk add --no-cache bash in the dockerfile) and run NPM install, it will install the dependencies in the /app folder without errors.

I don't know how to solve this. I hope somebody sess what I'm doing wrong.
Thanks.

_Output of docker build:_

```
Step 7/12 : ENV NPM_CONFIG_LOGLEVEL warn
 ---> Using cache
 ---> 9fdec208e92e
Step 8/12 : RUN npm install
 ---> Running in 0c0912ab16e5
added 355 packages in 24.476s
 ---> 57ed4e10162e
Removing intermediate container 0c0912ab16e5
Step 9/12 : RUN ls -al -R
 ---> Running in b05074ef2642
.:
total 20
drwxr-xr-x    3 root     root          4096 Nov  6 08:16 .
drwxr-xr-x   51 root     root          4096 Nov  6 08:16 ..
drwxr-xr-x    4 root     root          4096 Nov  6 08:14 app
-rw-r--r--    1 root     root          1540 Nov  6 05:14 package.json
-rw-r--r--    1 root     root           179 Nov  6 05:03 pm2.json
```

_My dockerfile:_

```
FROM keymetrics/pm2:8

# Bundle APP files
COPY app app/
COPY package.json .
COPY pm2.json .

# Install bash shell
# RUN apk add --no-cache bash

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Show current folder structure in logs
RUN ls -al -R

# Expose ports
EXPOSE 80 443 3333 43554

CMD [ "pm2-docker", "start", "pm2.json" ]
```
_My package.json file:_

```
{
  "name": "microservices",
  "version": "1.0.10",
  "description": "Broker microservice for cloud trader",
  "repository": {
    "type": "git",
    "url": "git+https://gitlab.com/edelacruz/cloudtrader-microservices"
  },
  "main": "index.js",
  "scripts": {
    "start": "pm2 start process.yml",
    "prestart": "pm2 stop process.yml && pm2 delete process.yml",
    "stop": "pm2 stop process.yml && pm2 delete process.yml",
    "test": "mocha ./test",
    "version:patch": "npm version patch -m 'Upgrade to %s'",
    "version:release": "npm version major",
    "push": "npm run version:patch && git push --tags origin master",
    "build": "npm test && npm run push",
    "docker-build": "docker build -t cloudtrader/microservices:latest .",
    "docker-run": "docker run --name micro -p 3333:3333 --net host cloudtrader/microservices:latest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "async": "^2.5.0",
    "debug": "^2.6.9",
    "ioredis": "^3.2.1",
    "jsonwebtoken": "^7.4.3",
    "mongodb": "^2.2.33",
    "querystring": "^0.2.0",
    "socket.io-client": "^2.0.4",
    "winston": "^2.4.0",
    "winston-loggly-bulk": "^2.0.1",
    "ws": "^3.2.0"
  },
  "devDependencies": {
    "chai": "^4.0.2",
    "chai-as-promised": "^7.1.1",
    "mocha": "^3.4.2",
    "standard": "^10.0.3"
  },
  "standard": {
    "env": [
      "mocha",
      "chai"
    ],
    "globals": [
      "describe",
      "context",
      "before",
      "beforeEach",
      "after",
      "afterEach",
      "it",
      "expect"
    ]
  }
}
```

**Comment by bmitchboxboat** [comment] 2017-11-08 20:24
The `VOLUME` line needs to be removed from the Dockerfile. Ref: https://stackoverflow.com/q/47188500/596285

**Comment by mdebord1** [comment] 2017-11-08 21:30
Confirmed the `VOLUME` line needs to be removed from the Dockerfile. 

I ran through the pm2 example fully working with `node_modules` folder intact by using this modified Dockerfile:

```
FROM node:alpine

RUN npm install pm2 -g

RUN mkdir /app

# Expose ports
EXPOSE 80 443 43554

WORKDIR /app

# Start process.yml
CMD ["pm2-docker", "start", "--auto-exit", "--env", "production", "process.yml"]
```

**Comment by eric-naguras** [comment] 2017-11-09 04:28
@bmitchboxboat @mdebord1 Thanks for your input.
I just changed the first few lines of my Dockerfile to 

```
FROM node:8-alpine
RUN npm install pm2 -g
RUN mkdir /app
WORKDIR /app

```
So in effect skipping the keymetrics image all together.
Now the dependencies are installed in my image.

I wonder why they use that volume statement in their Dockerfile.
I can't be the first one to run into this problem.

**Comment by henningvs** [comment] 2017-11-20 13:44
@eric-naguras Is this issue resolved? I don't see a way to get the keymetrics image running without going around it completely.

**Comment by mdebord1** [comment] 2017-11-20 19:22
@henningvs The OP closed this, This case wasn't touched by Keymetrics so just keep working around it until they see it. 

`FROM node:8-alpine
RUN npm install pm2 -g
RUN mkdir /app
WORKDIR /app`

**Comment by eric-naguras** [comment] 2017-11-21 03:38
@henningvs The only way I could get it working was by not using their image but creating my own as you can read above.

**Comment by henningvs** [comment] 2017-11-21 10:13
Thanks for the feedback! This was exactly what I was doing coming from your comments and it works for me. 
Nevertheless I would like to use the Images provided by keymetrics, what do you think about reopening the issue @eric-naguras ? Otherwise I would have to open a new one.

**Comment by eric-naguras** [comment] 2017-11-21 10:53
Better you open a new issue.
But they don't seem to be interested.

Cheers,
Eric.

**Comment by ash0080** [comment] 2017-12-28 17:58
same NOT work for me 

```
// works as expected
FROM node:8-alpine
WORKDIR /app
COPY . .
RUN npm install --production
RUN ls -al -R
```

```
// even if  the npm install return ok , the node_modules cannot be created, mkdir not work also
FROM keymetrics/pm2:8
WORKDIR /app
COPY . .
RUN npm install --production
RUN ls -al -R
```

I think there are maybe something wrong in this pm2 image,  perhaps permission error

**Comment by simonepri** [comment] 2017-12-30 18:42
I'm reopening the issue to dive into the problem.

I agree that the `VOLUME` should not be present. I will remove it as soon I get a feedback from @Unitech .

**Closed** 2018-01-03 14:48 UTC

**Comment by simonepri** [comment] 2018-01-03 15:16
We are publishing new tags that fixes the issue.

Please have a check here:
https://github.com/keymetrics/docker-pm2#tags-available

And let us know if everything works as expected now!

**Comment by sudo-bmitch** [comment] 2018-01-03 19:40
> Please have a check here:
> https://github.com/keymetrics/docker-pm2#tags-available

The URLs for the Debian Dockerfiles are missing "debian", they all 404.

**Comment by simonepri** [comment] 2018-01-03 19:45
@sudo-bmitch I'm able to access to them.
Can you post the link that is not working for you?

**Comment by sudo-bmitch** [comment] 2018-01-04 00:26
@simonepri Looks good now, I was checking at exactly the wrong time.
